# Generated by Django 6.1 on 2026-09-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects_delete_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('website', 'Website'), ('game', 'Game'), ('mobile app', 'Mobile App'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
