# Generated by Django 5.2.17 on 2026-09-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
