# Generated by Django 5.2.17 on 2026-09-15 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_academic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='thumbnail',
        ),
    ]
