# Generated by Django 5.2.17 on 2026-09-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_projects_ended_at_remove_projects_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='projects',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
