# Generated by Django 5.2.17 on 2026-09-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_projects_status_projects_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='thumbnail',
        ),
    ]
